#pragma once
#define GRID_SIZE 50
#define GENERATIONS 0
#define GENERATIONS_PER_SECOND (-1)

#define SCREEN_WIDTH_PX 1500
#define SCREEN_HEIGHT_PX 1000

#define CELL_SIZE_PX 15
#define CELL_BORDER_PX 1