#pragma once
#define GRID_SIZE 1000
#define GENERATIONS 100
#define GENERATIONS_PER_SECOND (-1)

#define SCREEN_WIDTH_PX 1500
#define SCREEN_HEIGHT_PX 1000

#define CELL_SIZE_PX 8
#define CELL_BORDER_PX 1
